CREATE DATABASE TAIKHOAN
go
use TAIKHOAN
go

CREATE TABLE Users(
	Userid INT IDENTITY(1,1) PRIMARY KEY,
	Username NVARCHAR(50) NOT NULL,
	PassW VARCHAR(250) NOT NULL,
	Email NVARCHAR(100) null
);
GO

SELECT* FROM Users